# Generated by Django 4.0.3 on 2022-03-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=15)),
                ('prezime', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('pretplatnik', models.BooleanField(default=False)),
                ('sifra', models.CharField(max_length=20)),
                ('slika_korisnika', models.ImageField(upload_to='slike')),
                ('broj_pretplatnika', models.IntegerField()),
            ],
        ),
    ]
