# Generated by Django 4.0.3 on 2022-05-25 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text_poruke', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to='profile_avatar')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Korisnik',
            },
        ),
        migrations.CreateModel(
            name='Pretplatnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Pretplatnici',
            },
        ),
        migrations.CreateModel(
            name='Recepti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('slika_jela', models.ImageField(upload_to='slike')),
                ('ocjena_jela', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20)),
                ('datum_objave', models.DateField(auto_now_add=True)),
                ('tezina_pripreme', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20)),
                ('vrijeme_pripreme', models.IntegerField()),
                ('ukupno_vrijeme_pripreme', models.IntegerField()),
                ('broj_osoba', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default=1, max_length=20)),
                ('opis_jela', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Recepti',
            },
        ),
        migrations.CreateModel(
            name='VrstaJela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_jela', models.CharField(choices=[('Sendvic', 'Sendvic'), ('Pita', 'Pita'), ('Pasta', 'Pasta'), ('Kolac', 'Kolac'), ('Peciva', 'Peciva')], default='Sendvic', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Vrsta jela',
            },
        ),
        migrations.CreateModel(
            name='VrstaObroka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_obroka', models.CharField(choices=[('Dorucak', 'Dorucak'), ('Rucak', 'Rucak'), ('Vecera', 'Vecera'), ('Poslastica', 'Poslastica')], default='Dorucak', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Vrsta obroka',
            },
        ),
        migrations.CreateModel(
            name='ZdravaHrana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_hrane', models.CharField(choices=[('DTL', 'Dijetalna'), ('GLF', 'Bez Glutena'), ('CAL', 'Niskokaloricna'), ('VEG', 'Veganska')], default='Dijetalna', max_length=3)),
                ('recepti_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
                ('vrsta_jela_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstajela')),
                ('vrsta_obroka_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstaobroka')),
            ],
            options={
                'verbose_name_plural': 'Zdrava hrana',
            },
        ),
        migrations.CreateModel(
            name='VideoRecepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_videa', models.CharField(max_length=120)),
                ('videolink', models.URLField()),
                ('korisnik_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnik')),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
            options={
                'verbose_name_plural': 'Video recepta',
            },
        ),
        migrations.CreateModel(
            name='Sastojci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_sastojka', models.CharField(max_length=50)),
                ('broj_kalorija_sastojka', models.IntegerField()),
                ('kolicina', models.CharField(max_length=200)),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
            options={
                'verbose_name_plural': 'Sastojci',
            },
        ),
        migrations.AddField(
            model_name='recepti',
            name='vrsta_jela_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstajela'),
        ),
        migrations.AddField(
            model_name='recepti',
            name='vrsta_obroka_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstaobroka'),
        ),
        migrations.CreateModel(
            name='ListaZelja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Lista želja',
            },
        ),
        migrations.CreateModel(
            name='CijenaRecepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
            options={
                'verbose_name_plural': 'Cijena recepta',
            },
        ),
    ]
