# Generated by Django 3.2.13 on 2022-07-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepti',
            name='ocjena_jela',
        ),
    ]
