# Generated by Django 3.2.13 on 2022-06-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='storefront.Recepti'),
        ),
    ]
