# Generated by Django 4.0.3 on 2022-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastojci',
            name='kolicina',
            field=models.CharField(max_length=150),
        ),
    ]
