# Generated by Django 4.0.3 on 2022-05-29 19:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptiSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
        ),
    ]
