# Generated by Django 4.0.3 on 2022-03-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_recepttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text_poruke', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NacinPripreme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_pripreme', models.IntegerField()),
                ('ukupno_vrijeme_pripreme', models.IntegerField()),
                ('broj_osoba', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default=1, max_length=20)),
                ('opis_jela', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pretplatnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recepti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('slika_jela', models.ImageField(upload_to='slike')),
                ('ocjena_jela', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20)),
                ('datum_objave', models.DateField()),
                ('kalorije', models.IntegerField()),
                ('tezina_pripreme', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20)),
                ('korisnik_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnici')),
                ('nacin_pripreme_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.nacinpripreme')),
            ],
        ),
        migrations.CreateModel(
            name='VrstaJela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_jela', models.CharField(choices=[('Sen', 'Sendvic'), ('Pit', 'Pita'), ('Pas', 'Pasta'), ('Kol', 'Kolac'), ('Pec', 'Peciva')], default='Dorucak', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaObroka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_obroka', models.CharField(choices=[('D', 'Dorucak'), ('R', 'Rucak'), ('V', 'Vecera'), ('P', 'Poslastica')], default='Dorucak', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ZdravaHrana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_hrane', models.CharField(choices=[('DTL', 'Dijetalna'), ('GLF', 'Bez Glutena'), ('CAL', 'Niskokaloricna'), ('VEG', 'Veganska')], default='Dijetalna', max_length=3)),
                ('recepti_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
                ('vrsta_jela_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstajela')),
                ('vrsta_obroka_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstaobroka')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRecepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_videa', models.CharField(max_length=120)),
                ('videolink', models.URLField()),
                ('korisnik_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnici')),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
        ),
        migrations.CreateModel(
            name='Sastojci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_sastojka', models.CharField(max_length=50)),
                ('broj_kalorija_sastojka', models.IntegerField()),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
        ),
        migrations.AddField(
            model_name='recepti',
            name='vrsta_jela_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstajela'),
        ),
        migrations.AddField(
            model_name='recepti',
            name='vrsta_obroka_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.vrstaobroka'),
        ),
        migrations.AddField(
            model_name='nacinpripreme',
            name='recepti_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti'),
        ),
        migrations.AddField(
            model_name='nacinpripreme',
            name='sastojak_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.sastojci'),
        ),
        migrations.CreateModel(
            name='ListaZelja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnici')),
            ],
        ),
        migrations.CreateModel(
            name='CijenaRecepta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.recepti')),
            ],
        ),
    ]
