# Generated by Django 3.2.13 on 2022-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_remove_recepti_ocjena_jela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepti',
            name='tezina_pripreme',
            field=models.CharField(choices=[('1', 'Jednostavno'), ('2', 'Srednje'), ('3', 'Komplikovano')], default=1, max_length=20),
        ),
    ]
