# Generated by Django 4.0.3 on 2022-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_sastojci_kolicina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepti',
            name='vrsta_jela_id',
        ),
        migrations.RemoveField(
            model_name='zdravahrana',
            name='vrsta_jela_id',
        ),
        migrations.AlterField(
            model_name='vrstaobroka',
            name='vrsta_obroka',
            field=models.CharField(choices=[('Dorucak', 'Dorucak'), ('Rucak', 'Rucak'), ('Vecera', 'Vecera'), ('Poslastica', 'Poslastica'), ('Uzina', 'Uzina')], default='Dorucak', max_length=10),
        ),
        migrations.DeleteModel(
            name='VrstaJela',
        ),
    ]
