# Generated by Django 4.0.3 on 2022-06-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_receptisteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepti',
            name='ukupno_vrijeme_pripreme',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recepti',
            name='vrijeme_pripreme',
            field=models.PositiveIntegerField(),
        ),
    ]
