# Generated by Django 4.0.3 on 2022-06-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_komentari_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentari',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnik'),
        ),
    ]
