# Generated by Django 4.0.3 on 2022-06-05 11:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_alter_recepti_ukupno_vrijeme_pripreme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptisteps',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
