# Generated by Django 4.0.3 on 2022-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_kontakt_nacinpripreme_pretplatnici_recepti_vrstajela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrstajela',
            name='vrsta_jela',
            field=models.CharField(choices=[('Sendvic', 'Sendvic'), ('Pita', 'Pita'), ('Pasta', 'Pasta'), ('Kolac', 'Kolac'), ('Peciva', 'Peciva')], default='Sendvic', max_length=10),
        ),
        migrations.AlterField(
            model_name='vrstaobroka',
            name='vrsta_obroka',
            field=models.CharField(choices=[('Dorucak', 'Dorucak'), ('Rucak', 'Rucak'), ('Vecera', 'Vecera'), ('Poslastica', 'Poslastica')], default='Dorucak', max_length=10),
        ),
    ]
