# Generated by Django 4.0.3 on 2022-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_alter_komentari_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentari',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='storefront.korisnik'),
        ),
        migrations.AddField(
            model_name='komentari',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='storefront.korisnik'),
        ),
    ]
