# Generated by Django 3.2.13 on 2022-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_alter_recepti_tezina_pripreme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepti',
            name='tezina_pripreme',
            field=models.CharField(choices=[('Jednostavno', 'Jednostavno'), ('Srednje', 'Srednje'), ('Komplikovano', 'Komplikovano')], default=1, max_length=20),
        ),
    ]
