# Generated by Django 4.0.3 on 2022-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_vrstajela_vrsta_jela_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceptTest',
        ),
        migrations.AlterModelOptions(
            name='cijenarecepta',
            options={'verbose_name_plural': 'Cijena recepta'},
        ),
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name_plural': 'Kontakt'},
        ),
        migrations.AlterModelOptions(
            name='korisnici',
            options={'verbose_name_plural': 'Korisnici'},
        ),
        migrations.AlterModelOptions(
            name='listazelja',
            options={'verbose_name_plural': 'Lista želja'},
        ),
        migrations.AlterModelOptions(
            name='nacinpripreme',
            options={'verbose_name_plural': 'Način pripreme'},
        ),
        migrations.AlterModelOptions(
            name='pretplatnici',
            options={'verbose_name_plural': 'Pretplatnici'},
        ),
        migrations.AlterModelOptions(
            name='recepti',
            options={'verbose_name_plural': 'Recepti'},
        ),
        migrations.AlterModelOptions(
            name='sastojci',
            options={'verbose_name_plural': 'Sastojci'},
        ),
        migrations.AlterModelOptions(
            name='videorecepta',
            options={'verbose_name_plural': 'Video recepta'},
        ),
        migrations.AlterModelOptions(
            name='vrstajela',
            options={'verbose_name_plural': 'Vrsta jela'},
        ),
        migrations.AlterModelOptions(
            name='vrstaobroka',
            options={'verbose_name_plural': 'Vrsta obroka'},
        ),
        migrations.AlterModelOptions(
            name='zdravahrana',
            options={'verbose_name_plural': 'Zdrava hrana'},
        ),
        migrations.RemoveField(
            model_name='nacinpripreme',
            name='sastojak_id',
        ),
        migrations.AddField(
            model_name='nacinpripreme',
            name='sastojak_id',
            field=models.ManyToManyField(blank=True, to='storefront.sastojci'),
        ),
    ]
