# Generated by Django 4.0.3 on 2022-05-27 10:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_remove_sastojci_broj_kalorija_sastojka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepti',
            name='vrsta_obroka_id',
        ),
        migrations.RemoveField(
            model_name='zdravahrana',
            name='vrsta_obroka_id',
        ),
        migrations.AddField(
            model_name='recepti',
            name='vrsta_obroka',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dorucak', 'Dorucak'), ('Rucak', 'Rucak'), ('Vecera', 'Vecera'), ('Poslastica', 'Poslastica'), ('Uzina', 'Uzina')], default='Dorucak', max_length=37),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VrstaObroka',
        ),
    ]
