# Generated by Django 3.2.13 on 2022-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_auto_20220618_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourites', to='storefront.Recepti'),
        ),
    ]
