# Generated by Django 3.2.13 on 2022-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_recepti_tezina_pripreme'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('video_src', models.CharField(max_length=20)),
                ('video', models.FileField(upload_to='videozapisi')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.RemoveField(
            model_name='videorecepta',
            name='korisnik_id',
        ),
        migrations.RemoveField(
            model_name='videorecepta',
            name='recept_id',
        ),
        migrations.DeleteModel(
            name='ListaZelja',
        ),
        migrations.DeleteModel(
            name='VideoRecepta',
        ),
    ]
