# Generated by Django 3.2.13 on 2022-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_auto_20220828_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipevideos',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video_poster'),
        ),
    ]
