# Generated by Django 3.2.13 on 2022-06-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_alter_korisnik_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='avatar',
            field=models.ImageField(default='profile_avatar/default_avatar.jpg', upload_to='profile_avatar'),
        ),
    ]
