# Generated by Django 3.2.13 on 2022-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_recipevideos_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='biografija',
            field=models.TextField(blank=True),
        ),
    ]
