# Generated by Django 3.2.13 on 2022-06-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_korisnik_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='biografija',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
