# Generated by Django 4.0.3 on 2022-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_korisnik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={'verbose_name_plural': 'Korisnik'},
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='avatar',
            field=models.ImageField(default='profile_avatar/default_avatar.png', upload_to='profile_avatar'),
        ),
    ]
