# Generated by Django 4.0.3 on 2022-05-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_alter_korisnik_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepti',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.korisnik'),
        ),
    ]
