# Generated by Django 4.0.3 on 2022-05-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_recepti_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sastojci',
            name='mjerna_jedinica',
            field=models.CharField(choices=[('GR', 'Grama'), ('ML', 'Mililitara'), ('KOM', 'Komada')], default='Grama', max_length=3),
        ),
        migrations.AlterField(
            model_name='recepti',
            name='datum_objave',
            field=models.DateField(auto_now_add=True),
        ),
    ]
