# Generated by Django 4.0.3 on 2022-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0015_sastojci_mjerna_jedinica_alter_recepti_datum_objave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastojci',
            name='mjerna_jedinica',
            field=models.CharField(choices=[('GR', 'Grama'), ('ML', 'Mililitara'), ('KOM', 'Komada')], default='Komada', max_length=4),
        ),
    ]
