# Generated by Django 4.0.3 on 2022-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0017_alter_sastojci_mjerna_jedinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastojci',
            name='mjerna_jedinica',
            field=models.CharField(choices=[('GR', 'Grama'), ('ML', 'Mililitara'), ('KOM', 'Komada')], default='GR', max_length=10),
        ),
    ]
