# Generated by Django 4.0.3 on 2022-05-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0018_alter_sastojci_mjerna_jedinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='sastojci',
            name='kolicina',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sastojci',
            name='mjerna_jedinica',
            field=models.CharField(choices=[('GR', 'Grama'), ('ML', 'Mililitara'), ('KOM', 'Komada')], default='Gram', max_length=10),
        ),
    ]
